<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>cc7e30c5-ce07-44fb-aeb5-15d6ea94cb81</groupId>
  <artifactId>testapi</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>mule-application</packaging>
  <name>testapi</name>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <app.runtime>4.11.0</app.runtime>
    <mule.maven.plugin.version>4.7.0</mule.maven.plugin.version>
  </properties>

  <!-- FIX 2: tells mvn deploy where to publish -->
  <distributionManagement>
    <repository>
      <id>anypoint-exchange-v3</id>
      <name>Anypoint Exchange V3</name>
      <url>https://maven.anypoint.mulesoft.com/api/v3/organizations/${project.groupId}/maven</url>
      <layout>default</layout>
    </repository>
  </distributionManagement>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-clean-plugin</artifactId>
        <version>3.2.0</version>
      </plugin>
      <plugin>
        <groupId>org.mule.tools.maven</groupId>
        <artifactId>mule-maven-plugin</artifactId>
        <version>${mule.maven.plugin.version}</version>
        <extensions>true</extensions>
        <!-- FIX 3: CloudHub 2.0 deploy config -->
        <configuration>
          <cloudhub2Deployment>
            <uri>https://anypoint.mulesoft.com</uri>
            <provider>MC</provider>
            <environment>${mule.env}</environment>
            <target>${anypoint.privatespace.name}</target>
            <applicationName>${project.artifactId}${app.url.env}</applicationName>
            <vCores>${app.vCores}</vCores>
            <replicas>${app.replicas}</replicas>
            <connectedAppClientId>${connectedAppClientId}</connectedAppClientId>
            <connectedAppClientSecret>${connectedAppClientSecret}</connectedAppClientSecret>
            <connectedAppGrantType>${connectedAppGrantType}</connectedAppGrantType>
            <properties>
              <mule.env>${mule.env}</mule.env>
              <mule.key>${mule.key}</mule.key>
              <anypoint.platform.client_id>${anypoint.platform.client_id}</anypoint.platform.client_id>
              <anypoint.platform.client_secret>${anypoint.platform.client_secret}</anypoint.platform.client_secret>
            </properties>
          </cloudhub2Deployment>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>org.mule.connectors</groupId>
      <artifactId>mule-http-connector</artifactId>
      <version>1.11.1</version>
      <classifier>mule-plugin</classifier>
    </dependency>
    <dependency>
      <groupId>org.mule.connectors</groupId>
      <artifactId>mule-sockets-connector</artifactId>
      <version>1.2.7</version>
      <classifier>mule-plugin</classifier>
    </dependency>
  </dependencies>

  <repositories>
    <repository>
      <id>anypoint-exchange-v3</id>
      <name>Anypoint Exchange</name>
      <url>https://maven.anypoint.mulesoft.com/api/v3/maven</url>
      <layout>default</layout>
    </repository>
    <!-- FIX 1: renamed to match pipeline's injected credentials -->
    <repository>
      <id>MuleRepository</id>
      <name>MuleSoft Releases Repository</name>
      <url>https://repository.mulesoft.org/nexus/repository/releases/</url>
      <layout>default</layout>
      <snapshots><enabled>false</enabled></snapshots>
    </repository>
  </repositories>

  <pluginRepositories>
    <pluginRepository>
      <id>MuleRepository</id>
      <name>MuleSoft Releases Repository</name>
      <layout>default</layout>
      <url>https://repository.mulesoft.org/nexus/repository/releases/</url>
      <snapshots><enabled>false</enabled></snapshots>
    </pluginRepository>
  </pluginRepositories>

  <!-- FIX 4: profiles pipeline expects -->
  <profiles>
    <profile>
      <id>non-experience-service</id>
    </profile>
    <profile>
      <id>experience-service</id>
    </profile>
  </profiles>

</project>